name: downloadable
description: downloadables
version: 1.0.0
homepage: https://github.com/ali2236/downloadable

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0

dev_dependencies:
  test: ^1.16.8
