name: downloadable
description: downloadables
version: 0.1.0
author: Ali Ghanabri <ali.gh2236@gmail.com>
homepage: https://github.com/ali2236/downloadable

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.8


#dev_dependencies:
#  flutter_test:
#    sdk: flutter
